[package]
name = "git-sync-backup"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4.5", features = ["derive"] }
die-exit = "0.5"
env_logger = "0.11"
log = "0.4"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread", "fs"] }
async-scoped = { version = "0.9", features = ["use-tokio"] }
whoami = "1.6"
config-file2 = { version = "0.4", features = ["toml"] }
