[package]
name = "git-sync-backup"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
git2 = "0.20"
thiserror = "2.0"
log = "0.4"
pretty_env_logger = "0.5"
fs_extra = "1.3"
machine-uid = "0.5"
rayon = "1.8"
home = "0.5"
config-file2 = "0.4.1"

[dev-dependencies]
tempfile = "3"

[[bin]]
name = "gsb"
path = "src/main.rs"
