[package]
name = "git-sync-backup"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.9"
git2 = "0.20"
thiserror = "2.0"
log = "0.4"
env_logger = "0.11"
hostname = "0.4"
fs_extra = "1.3"
machine-uid = "0.5"
rayon = "1.8"
home = "0.5"

[[bin]]
name = "gsb"
path = "src/main.rs"
